import React, { useState } from 'react';

/**
 * Example 2: Comprehensive Controlled Components
 * 
 * When forms get larger, creating a separate state variable for every input
 * (e.g., const [name, setName], const [age, setAge]) becomes messy.
 * 
 * Instead, we use a single unified state object and a "Universal Change Handler".
 * 
 * ==============================================================================
 * 🧠 UNDERLYING MECHANICS OF THIS COMPONENT:
 * ==============================================================================
 * This component demonstrates an advanced pattern for managing complex forms in React.
 * Instead of keeping track of multiple independent `useState` variables, we define
 * one single object that holds all the form fields. 
 * 
 * The real magic happens inside the `handleInputChange` function. By utilizing 
 * JavaScript ES6 features—specifically Object Destructuring and Computed Property Names—
 * we can write a single, reusable event handler that works for *any* input element 
 * inside our form. As long as the `<input>` element has a `name` attribute that 
 * precisely matches a key inside the `patientData` state object, the handler will 
 * know exactly which piece of state to update.
 * 
 * Furthermore, by using the spread operator (`...prevData`) inside the state updater 
 * function, we ensure that we create a fresh copy of the previous state while only 
 * modifying the specific field that was targeted. This respects React's core rule 
 * of state immutability.
 * ==============================================================================
 */
export const ComprehensivePatientRegistration = () => {
  // 1. Single unified state object holding all patient data fields
  const [patientData, setPatientData] = useState({
    fullName: "",
    phoneNumber: "",
    age: "",
    address: ""
  });

  // 2. The Universal Change Handler:
  // This single function handles every input field in the form!
  /*
   * 🛠️ HOW THE UNIVERSAL HANDLER WORKS:
   * 1. It receives the 'e' (event) object generated by the browser when the user types.
   * 2. It grabs the 'name' and 'value' from the element that triggered the event (e.target).
   * 3. It calls the state setter 'setPatientData' with an arrow function (functional update).
   * 4. It copies all existing state fields using the spread operator `...prevData`.
   * 5. It dynamically targets the property to update using Computed Property Names `[name]`.
   */
  const handleInputChange = (e) => {
    // Destructure the 'name' attribute and the new 'value' from the input element triggering the event
    const { name, value } = e.target; 

    setPatientData((prevData) => ({
      ...prevData,      // Spread operator keeps all existing fields untouched by copying them over
      [name]: value     // Computed property overwrites ONLY the field that changed (evaluates `name` variable as key)
    }));
  };

  // 3. Reset all fields instantly with a single empty object
  /*
   * When this function is called, we replace the entire `patientData` object 
   * with a fresh object containing empty strings for all fields. 
   * Because React detects this state change, it immediately re-renders the UI,
   * pushing these empty strings back into the 'value' props of our inputs,
   * effectively clearing the screen instantly.
   */
  const handleResetForm = () => {
    setPatientData({
      fullName: "",
      phoneNumber: "",
      age: "",
      address: ""
    });
  };

  return (
    <div className="p-6 bg-slate-900 border border-slate-800 rounded-2xl max-w-lg mx-auto text-white font-mono shadow-2xl">
      <h2 className="text-xl font-extrabold text-cyan-400 mb-6">🏥 Comprehensive Patient Portal</h2>

      <div className="space-y-4">
        {/* --- FIELD 1: FULL NAME --- */}
        <div>
          <label className="block text-xs text-slate-400 mb-1">Patient Full Name:</label>
          <input
            type="text"
            name="fullName"                  // MUST MATCH the exact key in state object ("fullName")
            value={patientData.fullName}     // Reads from the unified object to make this a 'Controlled' input
            onChange={handleInputChange}     // Calls the Universal Handler whenever the user types a character
            placeholder="e.g. Ahmed Mahmoud"
            className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl text-sm focus:border-cyan-500 focus:outline-none"
          />
        </div>

        {/* --- FIELD 2: PHONE NUMBER --- */}
        <div>
          <label className="block text-xs text-slate-400 mb-1">Phone Number:</label>
          <input
            type="text"
            name="phoneNumber"               // Targets 'phoneNumber' key in state
            value={patientData.phoneNumber}  // Controlled input value binding
            onChange={handleInputChange}
            placeholder="07900000000"
            className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl text-sm focus:border-cyan-500 focus:outline-none"
          />
        </div>

        {/* --- FIELD 3: AGE --- */}
        <div>
          <label className="block text-xs text-slate-400 mb-1">Patient Age:</label>
          <input
            type="number"
            name="age"                       // Targets 'age' key in state
            value={patientData.age}
            onChange={handleInputChange}
            placeholder="e.g. 35"
            className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl text-sm focus:border-cyan-500 focus:outline-none"
          />
        </div>

        {/* --- FIELD 4: ADDRESS --- */}
        <div>
          <label className="block text-xs text-slate-400 mb-1">Residential Address:</label>
          <input
            type="text"
            name="address"                   // Targets 'address' key in state
            value={patientData.address}
            onChange={handleInputChange}
            placeholder="City, District, Street..."
            className="w-full p-3 bg-slate-950 border border-slate-700 rounded-xl text-sm focus:border-cyan-500 focus:outline-none"
          />
        </div>
      </div>

      {/* --- LIVE STATE DEBUGGER --- */}
      {/* This helps students visualize how the state object updates in real-time */}
      {/* 
        JSON.stringify is used here to serialize our JS object into a readable string. 
        The 'null' argument is a replacer function (none used), and '2' indicates the number of spaces for indentation.
      */}
      <div className="mt-6 p-4 bg-slate-950/80 rounded-xl border border-dashed border-slate-700">
        <span className="text-[10px] text-amber-400 font-bold block mb-1">⚡ LIVE UNIFIED STATE OBJECT:</span>
        <pre className="text-xs text-emerald-400 overflow-x-auto leading-relaxed">
          {JSON.stringify(patientData, null, 2)}
        </pre>
      </div>

      {/* --- FORM ACTIONS --- */}
      <div className="mt-6 flex gap-3">
        <button
          onClick={handleResetForm}
          className="w-1/3 py-3 bg-slate-800 hover:bg-slate-700 rounded-xl font-bold text-xs text-slate-300 transition cursor-pointer"
        >
          🗑️ Clear All
        </button>
        <button
          // The button is disabled dynamically using short-circuit boolean logic. 
          // If fullName OR phoneNumber are empty strings (falsy), this evaluates to true.
          disabled={!patientData.fullName || !patientData.phoneNumber}
          className="w-2/3 py-3 bg-cyan-600 hover:bg-cyan-500 disabled:bg-slate-800 disabled:text-slate-600 rounded-xl font-bold text-sm transition cursor-pointer disabled:cursor-not-allowed"
        >
          ✅ Save Patient Record
        </button>
      </div>
    </div>
  );
};

